-- DevotionalHub hosted Supabase bootstrap
-- Generated by: npm run backend:bootstrap-file
-- Run this entire file ONCE in Supabase Dashboard -> SQL Editor.
-- It applies the version-controlled migrations and records their versions.

begin;

-- >>> 20260928120300_initial_devotionalhub_schema.sql
-- DevotionalHub initial data model
-- Content, editorial workflow, reader progress, downloads, and privacy-conscious analytics.

create extension if not exists pgcrypto with schema extensions;

create type public.app_role as enum ('editor', 'admin');
create type public.content_status as enum ('draft', 'in_review', 'scheduled', 'published', 'archived');
create type public.copyright_status as enum ('public_domain', 'original', 'licensed');
create type public.document_status as enum ('draft', 'published', 'archived');
create type public.activity_event_type as enum (
  'devotional_view',
  'devotional_complete',
  'prayer_complete',
  'bible_reading_complete',
  'bookmark',
  'share',
  'document_download'
);

-- -----------------------------------------------------------------------------
-- Accounts and staff roles
-- -----------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default 'Reader' check (char_length(display_name) between 1 and 80),
  avatar_url text,
  timezone text not null default 'Africa/Lagos' check (char_length(timezone) between 1 and 64),
  preferences jsonb not null default '{}'::jsonb check (jsonb_typeof(preferences) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.app_role not null,
  granted_by uuid references auth.users (id) on delete set null,
  granted_at timestamptz not null default now(),
  primary key (user_id, role)
);

-- These security-definer helpers avoid recursive RLS checks on user_roles.
create or replace function public.has_role(requested_role public.app_role)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = (select auth.uid())
      and role = requested_role
  );
$$;

create or replace function public.has_editor_access()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = (select auth.uid())
      and role in ('editor'::public.app_role, 'admin'::public.app_role)
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'Reader'
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- -----------------------------------------------------------------------------
-- Scripture, hymns, and devotional content
-- -----------------------------------------------------------------------------

create table public.bible_translations (
  code text primary key check (code ~ '^[A-Z0-9_-]{2,20}$'),
  name text not null,
  language_code text not null default 'en',
  can_republish boolean not null default false,
  copyright_notice text,
  source_url text,
  created_at timestamptz not null default now()
);

create table public.scripture_passages (
  id uuid primary key default extensions.gen_random_uuid(),
  translation_code text not null references public.bible_translations (code) on update cascade,
  reference text not null check (char_length(reference) between 2 and 120),
  passage_text text not null check (char_length(trim(passage_text)) > 0),
  source_url text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (translation_code, reference)
);

create table public.hymns (
  id uuid primary key default extensions.gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 180),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  author_name text,
  composer_name text,
  lyrics text not null check (char_length(trim(lyrics)) > 0),
  copyright_status public.copyright_status not null,
  attribution text,
  source_url text,
  license_notes text,
  is_active boolean not null default true,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint licensed_hymn_requires_notes check (
    copyright_status <> 'licensed'::public.copyright_status
    or nullif(trim(license_notes), '') is not null
  )
);

create table public.devotionals (
  id uuid primary key default extensions.gen_random_uuid(),
  devotional_date date not null unique,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 1 and 180),
  summary text check (summary is null or char_length(summary) <= 320),
  memory_verse_id uuid references public.scripture_passages (id) on delete restrict,
  main_passage_id uuid references public.scripture_passages (id) on delete restrict,
  message text not null default '',
  reflection_question text,
  action_point text,
  author_name text not null default 'DevotionalHub Editorial Team',
  status public.content_status not null default 'draft',
  seo_description text check (seo_description is null or char_length(seo_description) <= 320),
  created_by uuid references auth.users (id) on delete set null,
  reviewed_by uuid references auth.users (id) on delete set null,
  reviewed_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint publication_requires_complete_review check (
    status not in ('scheduled'::public.content_status, 'published'::public.content_status)
    or (
      memory_verse_id is not null
      and main_passage_id is not null
      and char_length(trim(message)) > 0
      and reviewed_by is not null
      and reviewed_at is not null
      and published_at is not null
    )
  )
);

create table public.topics (
  id uuid primary key default extensions.gen_random_uuid(),
  name text not null unique check (char_length(name) between 1 and 80),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  description text,
  created_at timestamptz not null default now()
);

create table public.devotional_topics (
  devotional_id uuid not null references public.devotionals (id) on delete cascade,
  topic_id uuid not null references public.topics (id) on delete cascade,
  primary key (devotional_id, topic_id)
);

create table public.prayer_points (
  id uuid primary key default extensions.gen_random_uuid(),
  devotional_id uuid not null references public.devotionals (id) on delete cascade,
  sort_order smallint not null check (sort_order > 0),
  content text not null check (char_length(trim(content)) > 0),
  scripture_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (devotional_id, sort_order)
);

create table public.devotional_hymns (
  devotional_id uuid primary key references public.devotionals (id) on delete cascade,
  hymn_id uuid not null references public.hymns (id) on delete restrict,
  note text,
  created_at timestamptz not null default now()
);

-- Every update stores the previous devotional state for editorial accountability.
create table public.devotional_revisions (
  id bigint generated always as identity primary key,
  devotional_id uuid not null references public.devotionals (id) on delete cascade,
  snapshot jsonb not null,
  changed_by uuid references auth.users (id) on delete set null,
  changed_at timestamptz not null default now()
);

create or replace function public.capture_devotional_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if to_jsonb(old) is distinct from to_jsonb(new) then
    insert into public.devotional_revisions (devotional_id, snapshot, changed_by)
    values (old.id, to_jsonb(old), (select auth.uid()));
  end if;

  return new;
end;
$$;

create trigger capture_devotional_revision_before_update
  before update on public.devotionals
  for each row execute procedure public.capture_devotional_revision();

-- -----------------------------------------------------------------------------
-- Date-based Bible reading plans
-- -----------------------------------------------------------------------------

create table public.reading_plans (
  id uuid primary key default extensions.gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 180),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  description text,
  start_date date not null,
  end_date date not null,
  is_active boolean not null default false,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create table public.reading_plan_days (
  id uuid primary key default extensions.gen_random_uuid(),
  reading_plan_id uuid not null references public.reading_plans (id) on delete cascade,
  plan_date date not null,
  day_number smallint not null check (day_number > 0),
  title text,
  introduction text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reading_plan_id, plan_date),
  unique (reading_plan_id, day_number)
);

create table public.reading_plan_items (
  id uuid primary key default extensions.gen_random_uuid(),
  reading_plan_day_id uuid not null references public.reading_plan_days (id) on delete cascade,
  sort_order smallint not null check (sort_order > 0),
  scripture_reference text not null check (char_length(scripture_reference) between 2 and 120),
  passage_id uuid references public.scripture_passages (id) on delete set null,
  created_at timestamptz not null default now(),
  unique (reading_plan_day_id, sort_order)
);

-- -----------------------------------------------------------------------------
-- Signed-in reader state
-- -----------------------------------------------------------------------------

create table public.devotional_progress (
  user_id uuid not null references auth.users (id) on delete cascade,
  devotional_id uuid not null references public.devotionals (id) on delete cascade,
  started_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  completed_at timestamptz,
  primary key (user_id, devotional_id)
);

create table public.prayer_progress (
  user_id uuid not null references auth.users (id) on delete cascade,
  prayer_point_id uuid not null references public.prayer_points (id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, prayer_point_id)
);

create table public.reading_progress (
  user_id uuid not null references auth.users (id) on delete cascade,
  reading_plan_item_id uuid not null references public.reading_plan_items (id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, reading_plan_item_id)
);

create table public.bookmarks (
  user_id uuid not null references auth.users (id) on delete cascade,
  devotional_id uuid not null references public.devotionals (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, devotional_id)
);

-- -----------------------------------------------------------------------------
-- Monthly DOCX files and aggregate activity
-- -----------------------------------------------------------------------------

create table public.monthly_documents (
  id uuid primary key default extensions.gen_random_uuid(),
  month_start date not null,
  version integer not null default 1 check (version > 0),
  title text not null check (char_length(title) between 1 and 180),
  file_path text not null check (char_length(trim(file_path)) > 0),
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  checksum_sha256 text check (checksum_sha256 is null or checksum_sha256 ~ '^[a-f0-9]{64}$'),
  status public.document_status not null default 'draft',
  generated_by uuid references auth.users (id) on delete set null,
  generated_at timestamptz not null default now(),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (month_start, version),
  check (extract(day from month_start) = 1),
  constraint published_document_requires_date check (
    status <> 'published'::public.document_status or published_at is not null
  )
);

create unique index one_published_document_per_month
  on public.monthly_documents (month_start)
  where status = 'published'::public.document_status;

-- No prayer text, email, IP address, or private notes are stored here. The app
-- should generate a random session UUID in the browser and respect analytics
-- consent. A session remains non-identifying when user_id is null.
create table public.activity_events (
  id bigint generated always as identity primary key,
  event_type public.activity_event_type not null,
  user_id uuid references auth.users (id) on delete set null,
  session_id uuid not null,
  devotional_id uuid references public.devotionals (id) on delete set null,
  prayer_point_id uuid references public.prayer_points (id) on delete set null,
  reading_plan_item_id uuid references public.reading_plan_items (id) on delete set null,
  monthly_document_id uuid references public.monthly_documents (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint event_metadata_is_small_object check (
    jsonb_typeof(metadata) = 'object' and pg_column_size(metadata) <= 4096
  )
);

-- -----------------------------------------------------------------------------
-- Shared triggers and indexes
-- -----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_profiles_updated_at before update on public.profiles
  for each row execute procedure public.set_updated_at();
create trigger set_scripture_passages_updated_at before update on public.scripture_passages
  for each row execute procedure public.set_updated_at();
create trigger set_hymns_updated_at before update on public.hymns
  for each row execute procedure public.set_updated_at();
create trigger set_devotionals_updated_at before update on public.devotionals
  for each row execute procedure public.set_updated_at();
create trigger set_prayer_points_updated_at before update on public.prayer_points
  for each row execute procedure public.set_updated_at();
create trigger set_reading_plans_updated_at before update on public.reading_plans
  for each row execute procedure public.set_updated_at();
create trigger set_reading_plan_days_updated_at before update on public.reading_plan_days
  for each row execute procedure public.set_updated_at();
create trigger set_monthly_documents_updated_at before update on public.monthly_documents
  for each row execute procedure public.set_updated_at();

create index devotionals_publication_lookup_idx
  on public.devotionals (devotional_date desc, published_at)
  where status in ('scheduled'::public.content_status, 'published'::public.content_status);
create index devotionals_status_idx on public.devotionals (status, devotional_date desc);
create index prayer_points_devotional_idx on public.prayer_points (devotional_id, sort_order);
create index devotional_topics_topic_idx on public.devotional_topics (topic_id, devotional_id);
create index reading_plan_days_date_idx on public.reading_plan_days (plan_date);
create index reading_plan_items_day_idx on public.reading_plan_items (reading_plan_day_id, sort_order);
create index devotional_progress_user_completed_idx on public.devotional_progress (user_id, completed_at);
create index prayer_progress_user_completed_idx on public.prayer_progress (user_id, completed_at desc);
create index reading_progress_user_completed_idx on public.reading_progress (user_id, completed_at desc);
create index activity_events_occurred_idx on public.activity_events (occurred_at desc);
create index activity_events_type_occurred_idx on public.activity_events (event_type, occurred_at desc);
create index activity_events_devotional_idx on public.activity_events (devotional_id, occurred_at desc)
  where devotional_id is not null;
create index activity_events_user_idx on public.activity_events (user_id, occurred_at desc)
  where user_id is not null;
create index activity_events_session_idx on public.activity_events (session_id, occurred_at desc);
-- <<< 20260928120300_initial_devotionalhub_schema.sql

-- >>> 20260928120400_row_level_security_and_admin_analytics.sql
-- DevotionalHub row-level security, grants, and admin reporting functions.

-- -----------------------------------------------------------------------------
-- Safe public-visibility helpers
-- -----------------------------------------------------------------------------

create or replace function public.devotional_is_public(requested_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.devotionals
    where id = requested_id
      and status in ('scheduled'::public.content_status, 'published'::public.content_status)
      and published_at is not null
      and published_at <= now()
      and devotional_date <= (now() at time zone 'Africa/Lagos')::date
  );
$$;

create or replace function public.reading_plan_is_public(requested_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.reading_plans
    where id = requested_id
      and is_active = true
  );
$$;

create or replace function public.reading_plan_day_is_public(requested_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.reading_plan_days as plan_day
    join public.reading_plans as plan on plan.id = plan_day.reading_plan_id
    where plan_day.id = requested_id
      and plan.is_active = true
  );
$$;

-- -----------------------------------------------------------------------------
-- Enable RLS everywhere in the public API schema
-- -----------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.bible_translations enable row level security;
alter table public.scripture_passages enable row level security;
alter table public.hymns enable row level security;
alter table public.devotionals enable row level security;
alter table public.topics enable row level security;
alter table public.devotional_topics enable row level security;
alter table public.prayer_points enable row level security;
alter table public.devotional_hymns enable row level security;
alter table public.devotional_revisions enable row level security;
alter table public.reading_plans enable row level security;
alter table public.reading_plan_days enable row level security;
alter table public.reading_plan_items enable row level security;
alter table public.devotional_progress enable row level security;
alter table public.prayer_progress enable row level security;
alter table public.reading_progress enable row level security;
alter table public.bookmarks enable row level security;
alter table public.monthly_documents enable row level security;
alter table public.activity_events enable row level security;

-- -----------------------------------------------------------------------------
-- Profiles and roles
-- -----------------------------------------------------------------------------

create policy "Readers can view their own profile"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()));

create policy "Readers can create their own profile"
  on public.profiles for insert to authenticated
  with check (id = (select auth.uid()));

create policy "Readers can update their own profile"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

create policy "Admins can manage all profiles"
  on public.profiles for all to authenticated
  using ((select public.has_role('admin'::public.app_role)))
  with check ((select public.has_role('admin'::public.app_role)));

create policy "Users can view their own staff role"
  on public.user_roles for select to authenticated
  using (user_id = (select auth.uid()));

create policy "Admins can manage staff roles"
  on public.user_roles for all to authenticated
  using ((select public.has_role('admin'::public.app_role)))
  with check ((select public.has_role('admin'::public.app_role)));

-- -----------------------------------------------------------------------------
-- Public content and editorial access
-- -----------------------------------------------------------------------------

create policy "Anyone can view republishable Bible translations"
  on public.bible_translations for select to anon, authenticated
  using (can_republish = true);

create policy "Admins can manage Bible translations"
  on public.bible_translations for all to authenticated
  using ((select public.has_role('admin'::public.app_role)))
  with check ((select public.has_role('admin'::public.app_role)));

create policy "Anyone can view passages from republishable translations"
  on public.scripture_passages for select to anon, authenticated
  using (
    exists (
      select 1
      from public.bible_translations
      where code = scripture_passages.translation_code
        and can_republish = true
    )
  );

create policy "Editors can manage Scripture passages"
  on public.scripture_passages for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view active approved hymns"
  on public.hymns for select to anon, authenticated
  using (is_active = true);

create policy "Editors can manage hymns"
  on public.hymns for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view published devotionals"
  on public.devotionals for select to anon, authenticated
  using ((select public.devotional_is_public(id)));

create policy "Editors can manage devotionals"
  on public.devotionals for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view topics"
  on public.topics for select to anon, authenticated
  using (true);

create policy "Editors can manage topics"
  on public.topics for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view topics on published devotionals"
  on public.devotional_topics for select to anon, authenticated
  using ((select public.devotional_is_public(devotional_id)));

create policy "Editors can manage devotional topics"
  on public.devotional_topics for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view prayer points on published devotionals"
  on public.prayer_points for select to anon, authenticated
  using ((select public.devotional_is_public(devotional_id)));

create policy "Editors can manage prayer points"
  on public.prayer_points for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view hymns on published devotionals"
  on public.devotional_hymns for select to anon, authenticated
  using ((select public.devotional_is_public(devotional_id)));

create policy "Editors can assign hymns"
  on public.devotional_hymns for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Editors can view devotional revision history"
  on public.devotional_revisions for select to authenticated
  using ((select public.has_editor_access()));

-- -----------------------------------------------------------------------------
-- Reading plans
-- -----------------------------------------------------------------------------

create policy "Anyone can view active reading plans"
  on public.reading_plans for select to anon, authenticated
  using (is_active = true);

create policy "Editors can manage reading plans"
  on public.reading_plans for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view days in active reading plans"
  on public.reading_plan_days for select to anon, authenticated
  using ((select public.reading_plan_is_public(reading_plan_id)));

create policy "Editors can manage reading plan days"
  on public.reading_plan_days for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

create policy "Anyone can view items in active reading plans"
  on public.reading_plan_items for select to anon, authenticated
  using ((select public.reading_plan_day_is_public(reading_plan_day_id)));

create policy "Editors can manage reading plan items"
  on public.reading_plan_items for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

-- -----------------------------------------------------------------------------
-- Private reader progress
-- -----------------------------------------------------------------------------

create policy "Readers control their devotional progress"
  on public.devotional_progress for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "Readers control their prayer progress"
  on public.prayer_progress for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "Readers control their Bible reading progress"
  on public.reading_progress for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "Readers control their bookmarks"
  on public.bookmarks for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- Admins can report on completion state, but no private journal content exists.
create policy "Admins can report on devotional progress"
  on public.devotional_progress for select to authenticated
  using ((select public.has_role('admin'::public.app_role)));

create policy "Admins can report on prayer progress"
  on public.prayer_progress for select to authenticated
  using ((select public.has_role('admin'::public.app_role)));

create policy "Admins can report on Bible reading progress"
  on public.reading_progress for select to authenticated
  using ((select public.has_role('admin'::public.app_role)));

-- -----------------------------------------------------------------------------
-- Monthly documents and analytics
-- -----------------------------------------------------------------------------

create policy "Anyone can view published monthly documents"
  on public.monthly_documents for select to anon, authenticated
  using (
    status = 'published'::public.document_status
    and published_at is not null
    and published_at <= now()
  );

create policy "Editors can manage monthly documents"
  on public.monthly_documents for all to authenticated
  using ((select public.has_editor_access()))
  with check ((select public.has_editor_access()));

-- Event insertion is intentionally reserved for trusted server code using the
-- Supabase secret key (service_role). This prevents clients from fabricating dashboard metrics.
create policy "Admins can view activity events"
  on public.activity_events for select to authenticated
  using ((select public.has_role('admin'::public.app_role)));

create policy "Admins can delete activity events"
  on public.activity_events for delete to authenticated
  using ((select public.has_role('admin'::public.app_role)));

-- -----------------------------------------------------------------------------
-- Explicit Data API grants (RLS still applies to every query)
-- -----------------------------------------------------------------------------

revoke all on all tables in schema public from anon, authenticated;

-- Publicly readable content.
grant select on table
  public.bible_translations,
  public.scripture_passages,
  public.hymns,
  public.devotionals,
  public.topics,
  public.devotional_topics,
  public.prayer_points,
  public.devotional_hymns,
  public.reading_plans,
  public.reading_plan_days,
  public.reading_plan_items,
  public.monthly_documents
  to anon, authenticated;

-- Signed-in reader state.
grant select, insert, update on public.profiles to authenticated;
grant select on public.user_roles to authenticated;
grant select, insert, update, delete on table
  public.devotional_progress,
  public.prayer_progress,
  public.reading_progress,
  public.bookmarks
  to authenticated;

-- Editors and admins receive access through RLS, not broader client keys.
grant insert, update, delete on table
  public.bible_translations,
  public.scripture_passages,
  public.hymns,
  public.devotionals,
  public.topics,
  public.devotional_topics,
  public.prayer_points,
  public.devotional_hymns,
  public.reading_plans,
  public.reading_plan_days,
  public.reading_plan_items,
  public.monthly_documents
  to authenticated;

grant select on public.devotional_revisions to authenticated;
grant select, insert, update, delete on public.user_roles to authenticated;
grant select, delete on public.activity_events to authenticated;

-- Trigger functions are not application RPCs.
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.capture_devotional_revision() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;

revoke all on function public.has_role(public.app_role) from public;
revoke all on function public.has_editor_access() from public;
revoke all on function public.devotional_is_public(uuid) from public;
revoke all on function public.reading_plan_is_public(uuid) from public;
revoke all on function public.reading_plan_day_is_public(uuid) from public;

grant execute on function public.has_role(public.app_role) to authenticated;
grant execute on function public.has_editor_access() to authenticated;
grant execute on function public.devotional_is_public(uuid) to anon, authenticated;
grant execute on function public.reading_plan_is_public(uuid) to anon, authenticated;
grant execute on function public.reading_plan_day_is_public(uuid) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- Admin-only reporting RPCs
-- -----------------------------------------------------------------------------

create or replace function public.get_admin_dashboard_summary(
  p_start_date date default (current_date - 29),
  p_end_date date default current_date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not public.has_role('admin'::public.app_role) then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  if p_start_date > p_end_date then
    raise exception 'Start date must be on or before end date' using errcode = '22007';
  end if;

  select jsonb_build_object(
    'periodStart', p_start_date,
    'periodEnd', p_end_date,
    'registeredUsers', (select count(*) from public.profiles),
    'publishedDevotionals', (
      select count(*)
      from public.devotionals
      where status in ('scheduled'::public.content_status, 'published'::public.content_status)
        and published_at <= now()
        and devotional_date <= (now() at time zone 'Africa/Lagos')::date
    ),
    'activeReaders', (
      select count(distinct session_id)
      from public.activity_events
      where occurred_at >= p_start_date::timestamptz
        and occurred_at < (p_end_date + 1)::timestamptz
    ),
    'devotionalViews', (
      select count(*)
      from public.activity_events
      where event_type = 'devotional_view'::public.activity_event_type
        and occurred_at >= p_start_date::timestamptz
        and occurred_at < (p_end_date + 1)::timestamptz
    ),
    'devotionalCompletions', (
      select count(*)
      from public.activity_events
      where event_type = 'devotional_complete'::public.activity_event_type
        and occurred_at >= p_start_date::timestamptz
        and occurred_at < (p_end_date + 1)::timestamptz
    ),
    'prayerCompletions', (
      select count(*)
      from public.activity_events
      where event_type = 'prayer_complete'::public.activity_event_type
        and occurred_at >= p_start_date::timestamptz
        and occurred_at < (p_end_date + 1)::timestamptz
    ),
    'bibleReadingCompletions', (
      select count(*)
      from public.activity_events
      where event_type = 'bible_reading_complete'::public.activity_event_type
        and occurred_at >= p_start_date::timestamptz
        and occurred_at < (p_end_date + 1)::timestamptz
    ),
    'documentDownloads', (
      select count(*)
      from public.activity_events
      where event_type = 'document_download'::public.activity_event_type
        and occurred_at >= p_start_date::timestamptz
        and occurred_at < (p_end_date + 1)::timestamptz
    )
  ) into result;

  return result;
end;
$$;

create or replace function public.get_admin_daily_activity(
  p_start_date date default (current_date - 29),
  p_end_date date default current_date
)
returns table (
  activity_date date,
  event_type public.activity_event_type,
  event_count bigint,
  unique_readers bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.has_role('admin'::public.app_role) then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  if p_start_date > p_end_date then
    raise exception 'Start date must be on or before end date' using errcode = '22007';
  end if;

  return query
  select
    (events.occurred_at at time zone 'Africa/Lagos')::date as activity_date,
    events.event_type,
    count(*) as event_count,
    count(distinct events.session_id) as unique_readers
  from public.activity_events as events
  where events.occurred_at >= p_start_date::timestamptz
    and events.occurred_at < (p_end_date + 1)::timestamptz
  group by 1, 2
  order by 1, 2;
end;
$$;

revoke all on function public.get_admin_dashboard_summary(date, date) from public;
revoke all on function public.get_admin_daily_activity(date, date) from public;
grant execute on function public.get_admin_dashboard_summary(date, date) to authenticated;
grant execute on function public.get_admin_daily_activity(date, date) to authenticated;
-- <<< 20260928120400_row_level_security_and_admin_analytics.sql

-- >>> 20260928120500_monthly_document_storage.sql
-- Private storage for generated monthly DOCX files.
-- Readers download through trusted server code that logs the event and returns a
-- short-lived signed URL. Direct public bucket access is intentionally disabled.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'monthly-devotionals',
  'monthly-devotionals',
  false,
  52428800,
  array['application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Editors can view monthly devotional files"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'monthly-devotionals'
    and (select public.has_editor_access())
  );

create policy "Editors can upload monthly devotional files"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'monthly-devotionals'
    and (select public.has_editor_access())
  );

create policy "Editors can update monthly devotional files"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'monthly-devotionals'
    and (select public.has_editor_access())
  )
  with check (
    bucket_id = 'monthly-devotionals'
    and (select public.has_editor_access())
  );

create policy "Editors can delete monthly devotional files"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'monthly-devotionals'
    and (select public.has_editor_access())
  );
-- <<< 20260928120500_monthly_document_storage.sql

-- >>> seed.sql
-- Safe lookup data for local development and new environments.
-- No copyrighted devotional messages, Bible passages, or hymn lyrics are seeded.

insert into public.bible_translations (
  code,
  name,
  language_code,
  can_republish,
  copyright_notice,
  source_url
)
values (
  'WEB',
  'World English Bible',
  'en',
  true,
  'The World English Bible is in the public domain.',
  'https://worldenglish.bible/'
)
on conflict (code) do update set
  name = excluded.name,
  language_code = excluded.language_code,
  can_republish = excluded.can_republish,
  copyright_notice = excluded.copyright_notice,
  source_url = excluded.source_url;

insert into public.topics (name, slug, description)
values
  ('Faith', 'faith', 'Trusting God in every season of life.'),
  ('Prayer', 'prayer', 'Growing in a consistent and sincere life of prayer.'),
  ('Hope', 'hope', 'Finding confident hope in God and His promises.'),
  ('Purpose', 'purpose', 'Living intentionally in response to God''s calling.'),
  ('Relationships', 'relationships', 'Honouring God in family, friendship, and community.'),
  ('Spiritual Growth', 'spiritual-growth', 'Developing Christlike character and spiritual maturity.'),
  ('Wisdom', 'wisdom', 'Applying biblical truth to everyday decisions.')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description;

insert into public.reading_plans (
  id,
  title,
  slug,
  description,
  start_date,
  end_date,
  is_active
)
values (
  '20260000-0000-4000-8000-000000000001'::uuid,
  'DevotionalHub 2026 Bible Reading Plan',
  'devotionalhub-2026',
  'The date-based daily Bible reading plan for 2026. Activate it after its daily assignments have been reviewed and imported.',
  '2026-01-01'::date,
  '2026-12-31'::date,
  false
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  start_date = excluded.start_date,
  end_date = excluded.end_date;
-- <<< seed.sql

-- Keep future Supabase CLI pushes in sync with this dashboard bootstrap.
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version text not null primary key
);
alter table supabase_migrations.schema_migrations add column if not exists statements text[];
alter table supabase_migrations.schema_migrations add column if not exists name text;
insert into supabase_migrations.schema_migrations (version, name, statements)
values ('20260928120300', 'initial_devotionalhub_schema', null)
on conflict (version) do update set name = excluded.name;
insert into supabase_migrations.schema_migrations (version, name, statements)
values ('20260928120400', 'row_level_security_and_admin_analytics', null)
on conflict (version) do update set name = excluded.name;
insert into supabase_migrations.schema_migrations (version, name, statements)
values ('20260928120500', 'monthly_document_storage', null)
on conflict (version) do update set name = excluded.name;

commit;
